### ISSUE TITLE
Consider using amplify_derive library

### ISSUE THREAD

**Issue by dr-orlovsky** [bitcoindevkit/rust-electrum-client#31]
This will help to have more ideomatic derive macros for Error conversions (instead of raw macros)

https://crates.io/crates/amplify_derive

**Comment by afilini** [comment]
I'm not a big fan of adding extra dependencies just to save a few lines of code to implement the `From` trait here and there. Unless there's something particularly broken I'd just keep our custom macros instead.

**Comment by dr-orlovsky** [comment]
Ok, agree. While it also gives you ability to simply implement Display for errors with doc comments and many other things, seems like all cases are already covered by the written code, taking into account #36
