### ISSUE TITLE
Make serde feature-gated

### ISSUE THREAD

**Issue by dr-orlovsky** [bitcoindevkit/rust-electrum-client#40]

**Comment by afilini** [comment]
What do you mean by this exactly? I'm pretty sure we need `serde` internally to parse the JSON, do you see any way we can remove it?

**Comment by dr-orlovsky** [comment]
Oh, true, nevermind. Was confused by the fact that serde is optional everywhere (and is a very heavy dependecy) and forgot on Electrum API specifics
