### ISSUE TITLE
Consider doin non-`.beta-*` versions

### ISSUE THREAD

**Issue by dr-orlovsky** [bitcoindevkit/rust-electrum-client#43]
Using `.beta/alpha/rc-*` in rust semver prevents from automatic upgrades; thus, if there is a patch version released the depenecies will not upgrade automatically. All `0.*` versions in rust semver are considered beta and unstable, so `beta` suffix is useful _only_ when you need to prevent downstream dependencies from automatic upgrades and in preparation of publishing final version on `crates.io`

**Comment by RCasatta** [comment]
we can close this, from 0.6.0 there is no beta in version
