### ISSUE TITLE
`Error` does not implement `std::error::Error`

### ISSUE THREAD

**Issue by thomaseizinger** [bitcoindevkit/rust-electrum-client#46]
Several error handling libraries in the ecosystem like `anyhow` depend on this.

Happy to send a PR for this!

**Comment by RCasatta** [comment]
I would ack that PR

**Comment by thomaseizinger** [comment]
Nvm, was already fixed in https://github.com/bitcoindevkit/rust-electrum-client/commit/efdc7d224354384359cf7615ad56c2b86c981274.
