### ISSUE TITLE
Off-by-one error for retries?

### ISSUE THREAD

**Issue by thomaseizinger** [bitcoindevkit/rust-electrum-client#47]
The default value for `retries` in the `Config` is 1.

The retry value is used here:

https://github.com/bitcoindevkit/rust-electrum-client/blob/7db9a1331b7bacce7c21b51582c3ee006a850985/src/client.rs#L57-L59

I think there is an off-by-one error here because effectively, a value of 1 means 0 **re**-tries because we fail after the first error so we never actually **re**-try the call. If we were to use `>` instead of `==` then we would actually retry the RPC call.

**Comment by RCasatta** [comment]
Yeah, I think the `Config` parameter is wrongly called `retry` but meaning attempts (as the error variant).
We can do one of the following:
* do what you suggest, changing the operator and the default value of `retry` to 0
* rename the field `retry` to `attempts: NonZeroU8`

**Comment by thomaseizinger** [comment]
> do what you suggest, changing the operator and the default value of retry to 0

I would suggest to leave the value of `retry` at 1 **and** change the operator. That would be a much more useful default in my experience.

We use the electrum-client through bdk and ran into this error on broadcasting a transaction after not having used the client for ~ 20 minutes. With a retry of 0, the experience is rather bad because all the calls to the client suddenly fail and you have to investigate why.

> * rename the field `retry` to `attempts: NonZeroU8`

I was thinking about that as well but refrained from suggesting it because it is confusing IMO.

I always expect at least 1 attempt to happen. No attempts don't make any sense. It feels weird having to use the type system to enforce that if we could just change the semantics of the field.

**Comment by RCasatta** [comment]
> I would suggest to leave the value of retry at 1 and change the operator.

SGTM
