### ISSUE TITLE
Use Decimal to represent fees value

### ISSUE THREAD

**Issue by survived** [bitcoindevkit/rust-electrum-client#53]
`estimate_fee` method returns `f64` that's not good for financial calculations. For purposes of this library, [`rust_decimal::Decimal`](https://docs.rs/rust_decimal/1.14.2/rust_decimal/index.html) should be just fine.

**Comment by afilini** [comment]
I don't think the precision of an f64 really is an issue. Even if you have the perfect fee estimation you are still constrained by the fact that you can't pay a fraction of a satoshi as fee, i.e. if you have a 200 byte tx you can either pay 200 sat in fee for a 1 sat/byte or 201 sats for a 1.005 sat/byte. I think there are far larger errors there than in the representation of an f64

**Comment by survived** [comment]
Fair enough, `f64` precision should be enough for using estimated fee only in the simplest calculations. E.g. in the case of 200byte transaction, you need to assume that error in `f64` won't happen with 10^5 precision (as you will multiply estimated fee by 200*1000). 

Just wanted to let you know that `Decimal` might be more sound, and it can be used in the same way as `f64`. Feel free to close the issue.

**Comment by afilini** [comment]
No problem, thanks for pointing that out!
