### ISSUE TITLE
Do a 0.9 RC1 based on rust-bitcoin 0.28.0-rc.1

### ISSUE THREAD

**Issue by dr-orlovsky** [bitcoindevkit/rust-electrum-client#63]
Can we pls follow the new rust-bitcoin release cycle and do a release candidate here basing on RC1 rust-bitcoin version, such that downstream crates can test taproot support? 

More details on taproot release cycle can be found in https://github.com/rust-bitcoin/rust-bitcoin/issues/773

**Comment by afilini** [comment]
Published now, it's in the `release/0.9.0-rc.x` branch
