### ISSUE TITLE
Add a trait to get the status of a transaction

### ISSUE THREAD

**Issue by ConorOkus** [bitcoindevkit/rust-electrum-client#79]
For example, we should be able to query for the confirmation status of a transaction and other more verbose information.

**Comment by notmandatory** [comment]
Looks like right now this lib only returns the "raw" bytes version of a transaction with [`transaction_get_raw(txid: &Txid)`](https://docs.rs/electrum-client/0.12.0/electrum_client/trait.ElectrumApi.html#tymethod.transaction_get_raw). Just to confirm, for this issue are you looking to add the "verbose" parameter option and get back all the extra transaction info specified here: https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-get
